# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c34e61a8-df13-4daa-9c65-d52abd216a27";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c34e61a8-df13-4daa-9c65-d52abd216a27".device = "/dev/disk/by-uuid/c34e61a8-df13-4daa-9c65-d52abd216a27";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0466-A4B7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [
    { 
      device = "/dev/mapper/luks-1b15fc4d-de1f-496a-b230-17459db44813"; 
      options = [ "nofail" "x-systemd.device-timeout=1s" ];
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
