# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d0707379-a68e-4599-97d0-3abd720c9f30";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d0707379-a68e-4599-97d0-3abd720c9f30".device = "/dev/disk/by-uuid/d0707379-a68e-4599-97d0-3abd720c9f30";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8278-A852";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-59ce3ec8-93d8-49e2-8d8f-ca31dff4cd1a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
