# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-60c879d1-901a-40f0-8b37-602e0bebcb43";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-60c879d1-901a-40f0-8b37-602e0bebcb43".device = "/dev/disk/by-uuid/60c879d1-901a-40f0-8b37-602e0bebcb43";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FF68-FF9F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-289e3cd7-c9cb-454f-8ca8-b74bc13ffd15"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
